app:
  build: ./dockerfiles/app/
  ports:
    - "8080:8080"
  links:
    - db:db
db:
  build: ./dockerfiles/db/
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
web:
  build: ./dockerfiles/web/
  ports:
    - "80:80"
  links:
    - app:app
